# Generated by Django 3.2.4 on 2021-06-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singularity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('description', models.TextField(max_length=4096)),
            ],
        ),
        migrations.RenameField(
            model_name='solaris',
            old_name='label',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='solaris',
            name='url',
        ),
    ]
